### ISSUE TITLE
为什么这里会有 logo 图片？

### ISSUE THREAD

**Issue by HydeSong** [cube-ui/cube-template#4]
这个build 目录里面为什么有个 [logo.png](https://github.com/cube-ui/cube-template/blob/master/template/build/logo.png) 图片？？

**Comment by AmyFoxFN** [comment]
谢谢反馈，估计是手抖了😂

**Comment by AmyFoxFN** [comment]
这是用 node-notifier 发操作系统通知时，用来做 icon 的。比如编译错误的时候，你会看到的vue通知
